export const Routes = {
  Login: 'Login',
  OTP: 'Otp',
  MyParentTabs: 'MyParentTabs',
  MyStudentTabs: 'MyStudentTabs',
  Menu: 'Menu',
  Settings: 'Settings',
  ChangeTheme: 'ChangeTheme',
  ChangePassword: 'ChangePassword',
  Notification: 'Notification',
  NotificationDetails: 'NotificationDetails',
  SchoolBills: 'SchoolBills',
  StudentBillDetail: 'StudentBillDetail',
  CreatePayment: 'CreatePayment',
  PaymentMethod: 'PaymentMethod',
  PaymentProcess: 'PaymentProcess',
  PaymentSuccess: 'PaymentSuccess',
  PaymentFail: 'PaymentFail',
  Invoice: 'Invoice',
  ViewTransaction: 'ViewTransaction',
  Academic: 'Academic',
  Home: 'Home',
};
